name: OBFUSCATION

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: sudo apt update && 
           sudo apt install -y python3.9 python3.9-distutils git rsync
    - name: pyarmor
      run: sudo /usr/bin/python3.9 $CI_PROJECT_DIR/Code_Obfuscation/get-pip.py && python3 -m pip install pyarmor 
           
    - name: remotepull
      run: |
        mkdir /tmp/obf_code && cd /tmp/obf_code && git clone https://venugopalnaiduch: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@github.com/neta-cybercns/cybercnsbackend_encrypted.git
        cd $CI_PROJECT_DIR
        python3.9 Code_Obfuscation/code_obfuscater.py $CI_PROJECT_DIR /tmp/obf_code/$CI_PROJECT_NAME
        cd /tmp/obf_code/$CI_PROJECT_NAME
        git status
        if [[ $(git ls-files -z --deleted | head -c1 | wc -c) -ne 0 ]];then git ls-files -z --deleted | xargs -0 git rm;fi;
        git add *
        git config --global user.email "venu@netalytics.co"
        git config --global user.name "venugopalnaiduch"
        echo $CI_COMMIT_MESSAGE
        git commit -m "$CI_COMMIT_MESSAGE"
        git push https://venugopalnaiduch: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@github.com/neta-cybercns/cybercnsbackend_encrypted.git
